@startuml
nwdiag {
   group {
    color = "#CCFFCC";
    description = "System under attack"
    EdgeRouterX;
    RaspberryPi;
    ESP32;
    RaspberryPi_container_mqttbroker;
    RaspberryPi_container_nodered;
    RaspberryPi_container_grafana;
    RaspberryPi_container_influxdb;
  }

  Internet [shape=cloud]
  Internet -- LabRouter
  network EmboLab {
    address = "172.27.224.0/20"
    LabRouter [address = "172.27.224.1"]
    EdgeRouterX [address = "172.27.224.x"]
    color=red
  }
  network your_LAN {
    color=palegreen
    address = "192.168.1.0/24"
    EdgeRouterX [address = "192.168.1.1"]
    RaspberryPi [address = "192.168.1.38"]
    RaspberryPi_container_mqttbroker [address = "192.168.1.129", description="RaspberryPi\nMQTT broker container"]
    RaspberryPi_container_grafana [address = "192.168.131.", description="RaspberryPi\nGrafana container"]
    RaspberryPi_container_influxdb [address = "192.168.1.130", description="RaspberryPi\nInfluxdb container"]
    RaspberryPi_container_nodered [address = "192.168.1.128", description="RaspberryPi\nNodered container"]
    Windows_laptop [address = "192.168.1.39"]
    KaliVM [address = "192.168.1.40",description="Attacker KaliVM\nBridged to your_LAN\nUSB wifi to your_WIFI"]
  }

  network your_WIFI {
    color=palegreen
    address = "192.168.99.0/24"
    RaspberryPi [address = "192.168.99.10",description="RaspberryPi:\nWiFi AP+DHCP\nNAT to LAN"]
    ESP32 [address = "192.168.99.50",description="ESP32:\nWiFi client\nMQTT publisher"]
    KaliVM [address = "192.168.99.51"]
  }
}
@enduml
